# Generated by Django 4.0.6 on 2022-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like_dislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк или Дизлайк', 'verbose_name_plural': 'Лайки и Дизлайки'},
        ),
        migrations.AddField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(default=False, verbose_name='Дизлайк'),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
