# Generated by Django 4.1.1 on 2022-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='видео с YouTube'),
        ),
    ]
